module.exports=function(app,usersDb){
    app.post('/api/create',(req,res)=>{
        usersDb.addUser(req.body).then(doc=>{
            res.send("Added")
        })
    })
    app.get('/api/plate/:plate',(req,res)=>{
        usersDb.getDriverInfo(req.params.plate).then(doc=>{
            res.json(doc)
        })
    })
}
